//! `strategy.matrix` expansion with GitHub's include/exclude rules.

use serde_json::{Map, Value};

/// GitHub's limit on jobs generated by one matrix.
pub const MAX_COMBINATIONS: usize = 256;

pub type Combination = Map<String, Value>;

/// Expand an already-evaluated matrix into its combinations, in GitHub's order.
pub fn expand(matrix: &Value) -> Result<Vec<Combination>, String> {
    let obj = match matrix {
        Value::Object(o) => o,
        other => {
            return Err(format!(
                "a matrix must be a mapping, got {}",
                type_name(other)
            ))
        }
    };

    let mut vectors: Vec<(&String, &Vec<Value>)> = Vec::new();
    for (key, value) in obj {
        if key == "include" || key == "exclude" {
            continue;
        }
        match value {
            Value::Array(items) if items.is_empty() => {
                return Err(format!("matrix vector '{key}' does not contain any values"))
            }
            Value::Array(items) => vectors.push((key, items)),
            other => {
                return Err(format!(
                    "matrix vector '{key}' must be a list, got {}",
                    type_name(other)
                ))
            }
        }
    }

    // Cartesian product; the first key varies slowest.
    let mut combos: Vec<Combination> = if vectors.is_empty() {
        vec![]
    } else {
        vec![Map::new()]
    };
    for (key, items) in &vectors {
        let mut next = Vec::with_capacity(combos.len() * items.len());
        for combo in &combos {
            for item in *items {
                let mut c = combo.clone();
                c.insert((*key).clone(), item.clone());
                next.push(c);
            }
        }
        combos = next;
        if combos.len() > MAX_COMBINATIONS * 16 {
            return Err(format!("matrix exceeds {MAX_COMBINATIONS} combinations"));
        }
    }

    for entry in list(obj.get("exclude"), "exclude")? {
        combos.retain(|c| {
            !entry
                .iter()
                .all(|(k, v)| c.get(k).is_some_and(|cv| deep_eq(cv, v)))
        });
    }

    let original: Vec<&String> = vectors.iter().map(|(k, _)| *k).collect();
    let mut extra: Vec<Combination> = Vec::new();
    for entry in list(obj.get("include"), "include")? {
        let mut added = false;
        for combo in combos.iter_mut() {
            let compatible = entry.iter().all(|(k, v)| {
                !original.contains(&k) || combo.get(k).is_some_and(|cv| deep_eq(cv, v))
            });
            if compatible {
                for (k, v) in entry {
                    combo.insert(k.clone(), v.clone());
                }
                added = true;
            }
        }
        if !added {
            extra.push(entry.clone());
        }
    }
    combos.extend(extra);

    if combos.is_empty() {
        return Err("the matrix produced no jobs".into());
    }
    if combos.len() > MAX_COMBINATIONS {
        return Err(format!(
            "the matrix produced {} jobs; GitHub allows at most {MAX_COMBINATIONS}",
            combos.len()
        ));
    }
    Ok(combos)
}

fn list<'a>(v: Option<&'a Value>, name: &str) -> Result<Vec<&'a Map<String, Value>>, String> {
    match v {
        None | Some(Value::Null) => Ok(vec![]),
        Some(Value::Array(items)) => items
            .iter()
            .map(|i| {
                i.as_object()
                    .ok_or_else(|| format!("matrix '{name}' entries must be mappings"))
            })
            .collect(),
        Some(_) => Err(format!("matrix '{name}' must be a list")),
    }
}

/// Equality used for matching matrix values: numbers compare numerically.
fn deep_eq(a: &Value, b: &Value) -> bool {
    match (a, b) {
        (Value::Number(x), Value::Number(y)) => x.as_f64() == y.as_f64(),
        (Value::Array(x), Value::Array(y)) => {
            x.len() == y.len() && x.iter().zip(y).all(|(a, b)| deep_eq(a, b))
        }
        (Value::Object(x), Value::Object(y)) => {
            x.len() == y.len()
                && x.iter()
                    .all(|(k, v)| y.get(k).is_some_and(|w| deep_eq(v, w)))
        }
        _ => a == b,
    }
}

fn type_name(v: &Value) -> &'static str {
    match v {
        Value::Null => "null",
        Value::Bool(_) => "a boolean",
        Value::Number(_) => "a number",
        Value::String(_) => "a string",
        Value::Array(_) => "a list",
        Value::Object(_) => "a mapping",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn product_order() {
        let c = expand(&json!({"os": ["a", "b"], "node": [1, 2]})).unwrap();
        assert_eq!(
            c,
            vec![
                json!({"os": "a", "node": 1}),
                json!({"os": "a", "node": 2}),
                json!({"os": "b", "node": 1}),
                json!({"os": "b", "node": 2}),
            ]
            .into_iter()
            .map(|v| v.as_object().unwrap().clone())
            .collect::<Vec<_>>()
        );
    }

    #[test]
    fn github_docs_include_example() {
        let m = json!({
            "fruit": ["apple", "pear"],
            "animal": ["cat", "dog"],
            "include": [
                {"color": "green"},
                {"color": "pink", "animal": "cat"},
                {"fruit": "apple", "shape": "circle"},
                {"fruit": "banana"},
                {"fruit": "banana", "animal": "cat"}
            ]
        });
        let c: Vec<Value> = expand(&m).unwrap().into_iter().map(Value::Object).collect();
        assert_eq!(
            c,
            vec![
                json!({"fruit": "apple", "animal": "cat", "color": "pink", "shape": "circle"}),
                json!({"fruit": "apple", "animal": "dog", "color": "green", "shape": "circle"}),
                json!({"fruit": "pear", "animal": "cat", "color": "pink"}),
                json!({"fruit": "pear", "animal": "dog", "color": "green"}),
                json!({"fruit": "banana"}),
                json!({"fruit": "banana", "animal": "cat"}),
            ]
        );
    }

    #[test]
    fn exclude_partial_match() {
        let m = json!({
            "os": ["macos", "windows"],
            "version": [12, 14, 16],
            "environment": ["staging", "production"],
            "exclude": [{"os": "macos", "version": 12, "environment": "production"}, {"os": "windows", "version": 16}]
        });
        assert_eq!(expand(&m).unwrap().len(), 12 - 1 - 2);
    }

    #[test]
    fn include_only() {
        let c = expand(&json!({"include": [{"a": 1}, {"a": 2}]})).unwrap();
        assert_eq!(c.len(), 2);
        assert_eq!(c[1]["a"], json!(2));
    }

    #[test]
    fn errors() {
        assert!(expand(&json!({"os": []})).is_err());
        assert!(expand(&json!({"os": "x"})).is_err());
        assert!(expand(&json!("x")).is_err());
        assert!(expand(&json!({"a": [1], "exclude": [{"a": 1}]})).is_err());
    }
}
